### ISSUE TITLE
Fatal Error: Fatal error: Class 'auth_plugin_manual' not found in /var/www/html/moodle_dev/auth/mcae/auth.php on line 31

### ISSUE THREAD

**Issue by Kathrin84** [danmarsden/moodle-auth_mcae#19]
Hi, 

I'm trying your plugin, but unfortunately I'm not able to work with it as I'm getting the above mentioned fatal error. Do you know if it's a fault on my side?
I'm using your latest version 2015112819 and my current Moodle version is Moodle 3.0.1+ (Build: 20151231)

Cheers,
Kathrin

**Comment by garyfagan1987** [comment]
I'm also getting the same error. I've added the following logic before the "auth_plugin_mcae" is extended:

`require_once($CFG->dirroot.'/auth/manual/auth.php');`

This has fixed the problem and plugin is now working correctly. Please advise if there is a better solution for this?

Thanks

**Comment by Sjiep** [comment]
I also got this error after I assigned the "mcae" as authenticator method to the user and then logged in with that user. 

However, I believe you should _not_ assign the "mcae" as authenticator method. The "mcae" runs silently in the background and on each login will assign the logged in user to the correct cohort (as configured) if this hasn't happened yet.

Authentication should still happen based on existing authentication methods or by a 'self-written' authentication plugin. 

Correct me if my thinking is wrong.

**Comment by danmarsden** [comment]
I'm not sure that in the long term this plugin makes sense as an authentication plugin type - I'm guessing it was written this way initially so that the user_authenticated_hook could be used. I've just written a patch that moves the handling into the user_created and user_updated events which mean that changing a user profile or adding a new user should trigger the code. If the login event is still needed we could leverage the new events api user_loggedin event.

Doing this would mean that the plugin might be better suited as a "local" plugin or maybe an "admin_tool" plugin instead of an Authentication plugin.

**Comment by danmarsden** [comment]
looks like manual/auth.php was added a while ago - closing this one as fixed.
